# 该镜像需要依赖的基础镜像
FROM java:8

ENV APP_PORT 3000
ENV APP_NAME eureka
ENV APP_HOME /springcloud/${APP_NAME}/

# 将当前目录下的jar包复制到docker容器的/目录下
ADD microservice-integration-eureka-0.0.1-SNAPSHOT.jar ${APP_HOME}/${APP_NAME}/microservice-integration-eureka.jar
ADD start.sh ${APP_HOME}/start.sh

# 声明服务运行端口
EXPOSE #{APP_PORT}

# 指定docker容器启动时运行jar包
ENTRYPOINT ["/bin/sh", "start.sh"]

# 指定维护者的名字
MAINTAINER haochencheng