apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins #服务在哪个空间内就写哪个空间
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: jenkins.k8s.com   #此service的访问域名
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080